export const initialStoreForm = {
  productStoreId: '',
  primaryStoreGroupId: '',
  storeName: '',
  companyName: '',
  title: '',
  subtitle: '',
  payToPartyId: '',
  inventoryFacilityId: '',
  oneInventoryFacility: 'N',
  checkInventory: 'Y',
  reserveInventory: 'Y',
  requireInventory: 'N',
  showOutOfStockProducts: 'Y',
  isImmediatelyFulfilled: 'N',
  isDemoStore: 'N',
  defaultLocaleString: '',
  defaultCurrencyUomId: 'USD',
  defaultTimeZoneString: '',
  defaultSalesChannelEnumId: '',
  orderNumberPrefix: '',
  visualThemeId: '',
  manualAuthIsCapture: 'N',
  prorateShipping: 'Y',
  prorateTaxes: 'Y',
  viewCartOnAdd: 'N',
  autoSaveCart: 'N',
  autoApproveOrder: 'Y',
  autoApproveInvoice: 'Y',
  daysToCancelNonPay: '',
  retryFailedAuths: 'Y',
  allowPassword: 'Y',
  defaultPassword: '',
  prodSearchExcludeVariants: 'Y',
  showPricesWithVatTax: 'N',
};

export function storeDtoToForm(dto) {
  return {
    productStoreId: dto.productStoreId || '',
    primaryStoreGroupId: dto.primaryStoreGroupId || '',
    storeName: dto.storeName || '',
    companyName: dto.companyName || '',
    title: dto.title || '',
    subtitle: dto.subtitle || '',
    payToPartyId: dto.payToPartyId || '',
    inventoryFacilityId: dto.inventoryFacilityId || '',
    oneInventoryFacility: dto.oneInventoryFacility || 'N',
    checkInventory: dto.checkInventory || 'Y',
    reserveInventory: dto.reserveInventory || 'Y',
    requireInventory: dto.requireInventory || 'N',
    showOutOfStockProducts: dto.showOutOfStockProducts || 'Y',
    isImmediatelyFulfilled: dto.isImmediatelyFulfilled || 'N',
    isDemoStore: dto.isDemoStore || 'N',
    defaultLocaleString: dto.defaultLocaleString || '',
    defaultCurrencyUomId: dto.defaultCurrencyUomId || '',
    defaultTimeZoneString: dto.defaultTimeZoneString || '',
    defaultSalesChannelEnumId: dto.defaultSalesChannelEnumId || '',
    orderNumberPrefix: dto.orderNumberPrefix || '',
    visualThemeId: dto.visualThemeId || '',
    manualAuthIsCapture: dto.manualAuthIsCapture || 'N',
    prorateShipping: dto.prorateShipping || 'Y',
    prorateTaxes: dto.prorateTaxes || 'Y',
    viewCartOnAdd: dto.viewCartOnAdd || 'N',
    autoSaveCart: dto.autoSaveCart || 'N',
    autoApproveOrder: dto.autoApproveOrder || 'Y',
    autoApproveInvoice: dto.autoApproveInvoice || 'Y',
    daysToCancelNonPay: dto.daysToCancelNonPay != null ? String(dto.daysToCancelNonPay) : '',
    retryFailedAuths: dto.retryFailedAuths || 'Y',
    allowPassword: dto.allowPassword || 'Y',
    defaultPassword: dto.defaultPassword || '',
    prodSearchExcludeVariants: dto.prodSearchExcludeVariants || 'Y',
    showPricesWithVatTax: dto.showPricesWithVatTax || 'N',
  };
}

export function storeFormToPayload(form, isEdit = false) {
  const payload = {
    storeName: form.storeName.trim(),
    primaryStoreGroupId: form.primaryStoreGroupId.trim() || undefined,
    companyName: form.companyName.trim() || undefined,
    title: form.title.trim() || undefined,
    subtitle: form.subtitle.trim() || undefined,
    payToPartyId: form.payToPartyId.trim() || undefined,
    inventoryFacilityId: form.inventoryFacilityId.trim() || undefined,
    oneInventoryFacility: form.oneInventoryFacility,
    checkInventory: form.checkInventory,
    reserveInventory: form.reserveInventory,
    requireInventory: form.requireInventory,
    showOutOfStockProducts: form.showOutOfStockProducts,
    isImmediatelyFulfilled: form.isImmediatelyFulfilled,
    isDemoStore: form.isDemoStore,
    defaultLocaleString: form.defaultLocaleString.trim() || undefined,
    defaultCurrencyUomId: form.defaultCurrencyUomId.trim() || undefined,
    defaultTimeZoneString: form.defaultTimeZoneString.trim() || undefined,
    defaultSalesChannelEnumId: form.defaultSalesChannelEnumId.trim() || undefined,
    orderNumberPrefix: form.orderNumberPrefix.trim() || undefined,
    visualThemeId: form.visualThemeId.trim() || undefined,
    manualAuthIsCapture: form.manualAuthIsCapture,
    prorateShipping: form.prorateShipping,
    prorateTaxes: form.prorateTaxes,
    viewCartOnAdd: form.viewCartOnAdd,
    autoSaveCart: form.autoSaveCart,
    autoApproveOrder: form.autoApproveOrder,
    autoApproveInvoice: form.autoApproveInvoice,
    daysToCancelNonPay: form.daysToCancelNonPay ? Number(form.daysToCancelNonPay) : undefined,
    retryFailedAuths: form.retryFailedAuths,
    allowPassword: form.allowPassword,
    defaultPassword: form.defaultPassword.trim() || undefined,
    prodSearchExcludeVariants: form.prodSearchExcludeVariants,
    showPricesWithVatTax: form.showPricesWithVatTax,
  };

  if (!isEdit) {
    payload.productStoreId = form.productStoreId.trim() || undefined;
  }

  return payload;
}
